### ISSUE TITLE
Testing for date-parts

### ISSUE THREAD

**Issue by bwiernik** [citation-style-language/csl-evolution#8]
The ability to test for the presence of specific date parts (e.g., for a month or day) comes up relatively frequently. Without this capability, some styles produce some weird output. For example, Chicago (author-date) shows both the year and the full date. If month and day are not provided, then this results in only the year being shown twice, which is entirely redundant. See here for a discussion: https://github.com/citation-style-language/styles/pull/3638#issuecomment-411472535

It seems like it would be fairly easy to add the option to test for specific date parts. I can see two options:
1. Add `issued-year`, `issued-month`, `accessed-year`, etc. as separate variables that can be tested for in `if` and `else-if`.
2. Add `date-part="year month day"` as a new attribute for `if` and `else-if` that, when specified along with a date variable in `variable=` will test for the presence of the relevant date part(s) in the specified date variable(s).

Number 1 seems like an easier and more consistent approach. I think that it would be good to still require all date parts to be rendered using `date`.

**Comment by cormacrelf** [comment]
CSL-M has this. Note that it isn't possible to enter dates with e.g. a month but not a year, so the way CSL-M lays it out (`if has-year-only="issued"` etc) is good, especially since you get to test multiple variables at once in the familiar way. My only issue is that there is a weird `-to` in `has-to-month-or-season` that I don't understand, but you could accept either that or `has-month-or-season` and be compatible.

 https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#has-day-extension

In general I think reusing efforts from CSL-M is a good idea, partly because it's already implemented in `citeproc-js`. (I'm also biased because I'm implementing a dual CSL/CSL-M processor, and more divergence is more work for me, whereas adding a CSL-M feature to CSL just means deleting a single line of code.)

**Comment by bwiernik** [comment]
Duplicate of https://github.com/citation-style-language/schema/issues/32
