### ISSUE TITLE
Some instances of outdated spec text

### ISSUE THREAD

**Issue by larsgw** [citation-style-language/csl-evolution#9]
There are a number of places where the specification is unclear about or inconsistent with what people are expected to do, and I think it would be a good idea to canonicalize those deviations.

  - the significance of the order of `cs:label` in `cs:names`: see [this post](https://discourse.citationstyles.org/t/names-label-position/1216)
  - the meaning of `genre` and `medium`: see [this post](https://discourse.citationstyles.org/t/inconsistencies-with-genre-and-medium/1475)
  - descriptions for the variables `container` & `original-author`
  - clarification that a variable suppressed by `cs:substitute` is considered empty for the purposes of determining whether to suppress the enclosing `cs:group` (that's what `citeproc-js` does, anyway)

**Comment by larsgw** [comment]
Found one more:

  - how `cs:group` and `cs:macro` should behave in case of empty variables: see [this post](https://discourse.citationstyles.org/t/groups-variables-and-missing-dates/1529/8?u=larsgw)

**Comment by bwiernik** [comment]
For `original-author`, I suggest this text:
The original creator of a work (e.g., the original songwriter or performer for a musical piece; the original developer or programmer for a piece of software; the original author of an adapted work such as a book adapted into a screenplay)

`container` should probably be deprecated (or at least not classified as a date). The spec text should just indicate that it should not be used, instead of "?".

**Comment by bwiernik** [comment]
These will all be resolved by open pull requests.
